version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2019!"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
   #  volumes:
   #    - /home/renatogroffe/Desenvolvimento/Docker/Volumes/MySql:/var/lib/mysql
   #  volumes:
   #    - ~/mysql_1:/var/lib/mysql
    networks:
      - mysql-compose-network

  phpmyadmin:
    depends_on:
      - mysqlsrv
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOSTS: "mysqlsrv"
    ports:
      - 8080:80
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge